import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../layout.tsx";
import Sidebar from "../../components/sidebar/sideBar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
      icon: [
        {
          url: "public/file.svg",
          href: "public/file.svg",
        },
      ],
    },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen w-full">
          <Sidebar/>
          <main className="flex-grow bg-gray-50 overflow-y-auto">
              {children}
          </main>
      </div>
      </body>
    </html>
  );
}
